server:
  port: 8761   #eureka服务的端口号
eureka:
  instance:
    hostname: eureka-server     #eureka实例的主机名（module名）
  client:
    register-with-eureka: false   #不把自己注册到eureka中，
    fetch-registry: false       #不从eureka上来获取服务的注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka   #注册中心服务的地址